"$schema" = "https://starship.rs/config-schema.json"

[bun]
symbol = " "

[character]
# success_symbol = "[>](bold green)"
# error_symbol = "[x](bold red)"
# vimcmd_symbol = "[<](bold green)"

[aws]
# format = "on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)"
format = "(on [$symbol$profile]($style)) "
style = "bold yellow"
symbol = " "

[azure]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[cmd_duration]
disabled = true
format = "[$duration]($style) "

[conda]
symbol = " "
format = "via [$symbol$environment]($style) "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "
format = "via [$symbol ]($style)"

[dotnet]
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = " tag "

[git_status]
# ahead = ">"
# behind = "<"
# diverged = "<>"
# renamed = "r"
# deleted = "x"

[gcloud]
symbol = "  "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
detect_files = ['package.json', '.node-version', '!bunfig.toml', '!bun.lockb']
disabled = true

[package]
symbol = " "
disabled = true

[pulumi]
symbol = " "
format = 'via [$symbol$stack]($style) '

[python]
symbol = " "
style = "bold green"
python_binary = [".venv/bin/python", "uv run python", "python"]

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[sudo]
symbol = "sudo "
