#!/usr/bin/env bash
# [ -z "$PS1"  ] && return
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Path to the bash it configuration
export BASH_IT="$HOME/.bash-it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='sexy'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

export VISUAL=vim
export EDITOR=$VISUAL
export HOST=matthias

# Cruise ROS
. /home/cruise/cruise/ros/scripts/run_setup.sh

# added by Anaconda 2.3.0 installer
# PATH="/home/mwis/anaconda/bin:$PATH"
PATH="$PATH:/usr/local/cuda/bin/"
export PATH

PYTHONPATH="/usr/local/lib/python2.7/dist-packages:$PYTHONPATH"
PYTHONPATH="/usr/lib/python2.7/dist-packages:$PYTHONPATH"
PYTHONPATH="/usr/lib/pymodules/python2.7/ansible:$PYTHONPATH"
PYTHONPATH=".:$PYTHONPATH"
export PYTHONPATH

alias makeflame='perf script | ~/FlameGraph/stackcollapse-perf.pl | ~/FlameGraph/flamegraph.pl > profile.svg && firefox profile.svg'
