#!/usr/bin/env bash
# [ -z "$PS1"  ] && return
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Path to the bash it configuration
export BASH_IT="$HOME/.bash-it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='sexy'

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

export VISUAL=vim
export EDITOR=$VISUAL
export BASH_SILENCE_DEPRECATION_WARNING=1

PATH=/usr/local/opt/python/libexec/bin:$PATH
PATH=$PATH:/usr/local/share/python
PATH=$PATH:/usr/local/sbin
PATH=$PATH:$HOME/bin
export PATH

[[ -s /usr/local/bin/virtualenvwrapper_lazy.sh ]] && source /usr/local/bin/virtualenvwrapper_lazy.sh

alias nb="workon notebook && jupyter notebook; deactivate; cd"
